name: Create Azure Resource Group

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name for the resource group (will be rg-cert-<name>)'
        required: true
        type: string

jobs:
  create-rg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group
        run: |
          az group create --name "rg-cert-${{ github.event.inputs.name }}" --location eastus
